### ISSUE TITLE
How to load some Extensions ? 

### ISSUE THREAD

**Issue by Portekoi** [theNBS/ng2-adsk-forge-viewer#10]
I'm sorry for the question but I do not understand how to load, for example, 2 extensions.

I've create 2 files : `hello.extension.ts` and `good-bye.extension.ts`

I've try to inject in the ctor of the `AppComponent` but It's not working because of the missing provider (normal)

Can you explain how to do it?

Thanks for your code and your help !

**Comment by alansmithnbs** [comment]
Thanks for reporting @Portekoi - I've had a look at the issue and am working on a fix. I'll have a new package published and some instructions in the next day or two.

**Comment by alansmithnbs** [comment]
@Portekoi I have updated the library and published a new version - 0.1.2 to better support custom extensions. Apologies - but this library is still a work in progress and I've not exercised everything.

I've update my example on StackBlitz to demonstrate how an extension can be created and registered -(https://stackblitz.com/edit/angular-forge-viewer).

Let me know how you get on - I'll leave this issue open for now.
