### ISSUE TITLE
UI.Button is not available

### ISSUE THREAD

**Issue by breivald** [theNBS/ng2-adsk-forge-viewer#11]
**Is your feature request related to a problem? Please describe.**
We are using your module to use forge viewer in a SharePoint framework webpart but a requirement led to that we needed to add a button to the toolbar. However this was not implemented when I looked through the module

**Describe the solution you'd like**
Add Autodes.Viewing.UI.Button to module

**Comment by alansmithnbs** [comment]
I've added typings for UI.Button and published a new version of the module. I've included a demonstration of how to get the [Autodesk Toolbar sample](https://forge.autodesk.com/en/docs/viewer/v6/tutorials/toolbar-button/) working on my [stackblitz project](https://stackblitz.com/edit/angular-forge-viewer). Let me know how you get on.

**Comment by breivald** [comment]
Hi, I get these errors when running ng build in my project. Don't know if it's because I'm using Angular 7.0.4. Anything you can verify ? 

ERROR in node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(115,33): error TS2312: An interface may only extend a class or another interface.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(117,4): error TS1036: Statements are not allowed in ambient contexts.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(574,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(574,20): error TS2304: Cannot find name 'Toolbar'.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(807,15): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(852,7): error TS2416: Property 'Event' in type 'RadioButtonGroup' is not assignable to the same property in base type 'ControlGroup'.
  Type '{ ACTIVE_BUTTON_CHANGED: string; }' is not assignable to type '{ VISIBILITY_CHANGED: string; COLLAPSED_CHANGED: string; }'.
    Property 'VISIBILITY_CHANGED' is missing in type '{ ACTIVE_BUTTON_CHANGED: string; }'.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(852,15): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(864,15): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(870,15): error TS1039: Initializers are not allowed in ambient contexts.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(877,19): error TS2304: Cannot find name 'State'.
node_modules/ng2-adsk-forge-viewer/src/component/viewer-typings.d.ts(882,23): error TS2304: Cannot find name 'State'.

**Comment by alansmithnbs** [comment]
Thanks @breivald I'll look in to this - I did add a few new types for the Toolbar and UI buttons. Looks like I might have messed up some of the typings - but guessing it might be related to Angular 7/typescript 3.x.
