### ISSUE TITLE
Get viewer container from Extension

### ISSUE THREAD

**Issue by breivald** [theNBS/ng2-adsk-forge-viewer#12]
hi and thanks for adding the features with the UI buttons :) Seems to work. 

But I found out when I was trying the get the HTML element from the viewer (usually viewer.container) that is was not implemented in the typings.ts. I need it to create a new dockingpanel 

Is this something you can add quickly ?

thanks
br Mattias

**Comment by alansmithnbs** [comment]
Hi @breivald, thanks for your feedback good to know the UI buttons are working.

I've added some of the missing typings for viewer.container etc and have published a new version of the module. The docking panel API isn't something I've used - so if you run in to problems it would be good to get a small sample of code representing what you're trying to do if possible so I can get the typings correct and put together a small demonstrate how to get docking panels working.
