### ISSUE TITLE
Invite to contribute to official definitions 

### ISSUE THREAD

**Issue by dukedhx** [theNBS/ng2-adsk-forge-viewer#13]
Hi Alan,

I am Bryan Huang from Autodesk Developer Network. Hope this finds you well.

In response to community feedback we are working on official TypeScript definitions for our Forge SDK and Viewer.js which will be released to DefinitelyTyped once done. Here’s our preliminary work so far: 
https://github.com/cyrillef/forge-api.typescript

So I am wondering - seeing what you’ve done here which is so amazing BTW - if you’d like to contribute to our official work? Feel free to drop me a line on forge.help@autodesk.com if you’d like to continue our conversation in private. Look forward to hearing from you!

Cheers,
Bryan

**Comment by dukedhx** [comment]
Hi Alan @alansmithnbs 
Since we haven’t heard from you I’d start to merge your work to our definitions. Let us know if this works against your wished and if you’d like stay anonymous on the closing credits :). Thanks and take care!

Cheers,
Bryan

**Comment by alansmithnbs** [comment]
@dukedhx Hi Bryan - seems my email got lost somewhere - apologies. I'll just respond on here. I'm really glad to hear that Autodesk are creating TypeScript typings for Forge. I'd be more than happy to contribute to your official work - let me know if i can help in any way. Happy to appear on the closing credit too.

Thanks,

Alan

**Comment by dukedhx** [comment]
Sorry Alan your email was blocked by our anti-spam (which is usually not as harsh with the real spam ...) and I will get to you once I got the repo ready for us to work on. Thrilled to have you on board! Thanks!
