### ISSUE TITLE
Can't compile in Angular 7

### ISSUE THREAD

**Issue by yakeer** [theNBS/ng2-adsk-forge-viewer#14]
Trying to compile in angular 7.

It gives an error in rxjs/Observables and so..
If I change it to rxjs it compiles fine.

Can you fix it?

**Comment by alansmithnbs** [comment]
@yakeer thanks for reporting. If you check out the [stackblitz project](https://stackblitz.com/edit/angular-forge-viewer), the viewer component does work with Angular 7. However, it's currently built to target Angular 5 using a pre-Angular 6 component build process. It is therefore using an old RxJS library that requires [rxjs-compat](https://www.npmjs.com/package/rxjs-compat) to be included in your project. Adding rxjs-compat should fix the problem - if not please let me know.

P.S. We're open to pull requests.

**Comment by yakeer** [comment]
Hey,
Thanks for your answer.

Can you validate that your stackblitz actually works?
I've tried to put my auth token and my urn into the parameters, but the draw won't show.
No errors or anything, just a blank page :/

If I can get the stackblitz to work, I will definitely put a pull request with the required fixes for native angular 7.

**Comment by alansmithnbs** [comment]
Not sure what's going on for you - but I paste in a token and urn and the viewer fires up...🤷‍♂️
My urn is Base64 encoded - and looks a bit like this dXJuOmFkc2sub2JqZWN0czpvcy5vYmplY3Q6dG9...<sniped>

<img width="1287" alt="screenshot 2019-01-25 at 11 14 33 pm" src="https://user-images.githubusercontent.com/7983234/51777902-1b631500-20f7-11e9-938b-7d0721cf7b5b.png">

**Comment by yakeer** [comment]
Yeah, mine too is base64 endoded, and still viewer does not fire up. 
I'm trying with chrome actually, but it doesn't work with Safari as well.

I'm taking the AuthToken I'm getting from the server.. weird.

**Comment by yakeer** [comment]
Got it to work only after adding the (onDocumentChanged)="documentChanged($event)" to the stackblitz.
FYI.

**Comment by alansmithnbs** [comment]
Interesting - glad you got to the bottom of the issue. Can I ask what file type you are trying to view. I predominantly translate and view Revit files. Just wondered if you are trying to view something else that isn't taken care of in the default logic used to load the the first viewable.
