### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by rahulshinde11** [theNBS/ng2-adsk-forge-viewer#18]
I have an error while importing to to appmodule

    ERROR in node_modules/ng2-adsk-forge-viewer/lib/component/viewer.component.d.ts(1,23): error TS2688: Cannot find type definition file for 'forge-viewer'.
    node_modules/ng2-adsk-forge-viewer/lib/component/viewer.component.d.ts(8,15): error TS2503: Cannot find namespace 'Autodesk'.
    node_modules/ng2-adsk-forge-viewer/lib/component/viewer.component.d.ts(10,13): error TS2503: Cannot find namespace 'Autodesk'.
    node_modules/ng2-adsk-forge-viewer/lib/component/viewer.component.d.ts(13,11): error TS2503: Cannot find namespace 'Autodesk'.

How can I fix this?

**Comment by yakeer** [comment]
How did you manage to solve it?

**Comment by rahulshinde11** [comment]
I forgot about the typings
https://forge.autodesk.com/blog/typescript-definitions-forge-viewer-and-nodejs-client-sdk-now-available

**Comment by alansmithnbs** [comment]
Thanks for raising this issue and for following up with more detail. I'll re-open this issue - asthe last comment helped me identify that the package.json shipped with the component is missing the dependencies on the typings etc which is leading to build errors. I'll try to get around to fixing this as soon as I can.

**Comment by alansmithnbs** [comment]
Forge typings are declared as a peer dependency in v1.2.0
