### ISSUE TITLE
Two Forge Viewer in single application

### ISSUE THREAD

**Issue by SamuJB** [theNBS/ng2-adsk-forge-viewer#21]
I am enable to create two Forge Viewer in single application. I have created two viewer but all model loads only in first Forge viewer and second Forge viewer is not working. I think the issue is Angular Forge Viewer component is using same container Id.

I am using ng2-adsk-forge-viewer npm library. so kindly suggest any solution or idea that can be worked.

**Comment by alansmithnbs** [comment]
Thanks for reporting - will look to fix this in the next release.

**Comment by alansmithnbs** [comment]
Fix included in v1.2.2.
