### ISSUE TITLE
Cors issues fetching from 

### ISSUE THREAD

**Issue by Khuarn** [theNBS/ng2-adsk-forge-viewer#28]
Hello :) 

I have some CORS issues fetching from the FORGE api with your package. below is the code I am using to fetch from the api 
![image](https://user-images.githubusercontent.com/57445200/97679230-4e3cf880-1a95-11eb-8483-7c02f8a8f1b3.png)

How should we solve this CORS issue?

          this.viewerOptions = {
                initializerOptions: {
                    env: 'AutodeskProduction',
                    getAccessToken: (onGetAccessToken: (token: string, expire: number) => void) => {
                        const expireTimeSeconds = 60 * 30;
                        onGetAccessToken(ACCESS_TOKEN, expireTimeSeconds);
                    },

                    api: 'derivativeV2',
                    enableMemoryManagement: true,
                },
                viewerConfig: {
                    extensions: [
                        
                    ],
                    theme: 'bim-theme',
                },
                onViewerScriptsLoaded: () => {

                },
                onViewerInitialized: (args: ViewerInitializedEvent) => {
                    args.viewerComponent.DocumentId = this.documentId;
                    //Create list in viewer details
                    args.viewerComponent.onObjectTreeCreated.subscribe(event => {
                        this.documentChanged(args);
                    });
                    args.viewerComponent.onGeometryLoaded.subscribe(event => {
                        if (this.elements.length <= 0) {
                            this.showWarning = true;
                        }
                        this.eventEmitterService.onInvokeUpdateElements(this.elements);
                        this.loaderService.removeLoader("viewerLoader");
                    })
                },
            };

**Comment by alansmithnbs** [comment]
Closing this issue
