### ISSUE TITLE
Support for newer Angular versions (^9)

### ISSUE THREAD

**Issue by Theuno** [theNBS/ng2-adsk-forge-viewer#31]
**Is your feature request related to a problem? Please describe.**
Currently Angular v8 is no longer under support. Versions 9, 10, 11 are now supported.

**Describe the solution you'd like**
Support for newer versions of Angular

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by alansmithnbs** [comment]
Thanks for raising - good timing! As I have actually just published a new version of the libary v1.2.6 which upgraded all dependencies to Angular 11.
