### ISSUE TITLE
How to Make Autodesk Viewer Perspective by Default?

### ISSUE THREAD

**Issue by anjaliTandel20** [theNBS/ng2-adsk-forge-viewer#36]

**Comment by alansmithnbs** [comment]
One solution would be to add a handler for the onGeometryLoaded event and set the camera to perspective there:

app.component.html:

```
<adsk-forge-viewer [viewerOptions]="viewerOptions"
                   (onSelectionChanged)="selectionChanged($event)"
                   (onGeometryLoaded)="geometryLoaded($event)"></adsk-forge-viewer>
```

app.component.ts:

```
...
  public geometryLoaded(event: GeometryLoadedEventArgs) {
    // event.target is a reference to the viewer object
    event.target.navigation.toPerspective();
  }
...
```

I'm not sure if there is a way of setting the default view as part of initialisation options. It may be worth asking on StackOverflow (https://forge.autodesk.com/en/support/get-help) if the above doesn't work for you.
