### ISSUE TITLE
Not loading with new version

### ISSUE THREAD

**Issue by juanpalf** [theNBS/ng2-adsk-forge-viewer#37]
Since the last forge update, this code and example are not working anymore....

**Comment by alansmithnbs** [comment]
@juanpalf Hi Juan, do you have any more information about what is not working - reproduction steps, error messages or screengrabs? I have update the Stackblitz example and it appears to be working (https://stackblitz.com/edit/angular-forge-viewer); the integration test app is also working locally.

**Comment by juanpalf** [comment]
created a new token and used a previously tested URN
404 error?... also tried uploading a new file (it is a .dwg)
![image](https://user-images.githubusercontent.com/23057405/115584198-3601a580-a290-11eb-9680-4f60cce7df83.png)

this same file and URN was tested last Friday ('2021/04/16') and loaded correctly...

**Comment by alansmithnbs** [comment]
I just updated the stackblitz demo before responding - I don't see any of those errors :-(
It might be worth trying the "Open in New Window" button or closing and re-opening the live preview as I have seen issues loading some of my models.

![image](https://user-images.githubusercontent.com/7983234/115587338-7cbdc280-a2c5-11eb-976b-73203fd8ae67.png)

**Comment by juanpalf** [comment]
It's working now... Learned (the hard way) you *must* translate the model every time you want to display it.... this is the only change I made and this time the model loaded correctly... 

Remember the translation service costs 0.2 credits for simple jobs in Autodesk forge...
