### ISSUE TITLE
3D Markup Extension

### ISSUE THREAD

**Issue by deunrandyvt** [theNBS/ng2-adsk-forge-viewer#39]
Hello!

First of all, thank you for this awesome forge library for angular. 

I have integrated it to my sample project and was looking at creating custom markups. I also read about this article https://forge.autodesk.com/blog/3d-markup-icons-and-info-card and was wondering if there is an available counterpart in this library? 

Thank you in advance!

**Comment by alansmithnbs** [comment]
Hi!

Thanks for the feedback. I had a look at that extension and was able to get something working - but have to admit I had a few issues as the extension looks to target an old version of the viewer. It was difficult to get anything working in a viewer version > 7.0 - and even in v7.0.0 it has a few glitches:

![image](https://user-images.githubusercontent.com/7983234/123554294-367a5900-d777-11eb-9c14-1c398c86e93e.png)

I've created a sample angular app to demonstrate how to convert the extension to one compatible with this library
[forge-extension.zip](https://github.com/theNBS/ng2-adsk-forge-viewer/files/6722016/forge-extension.zip) but it definitely has some "quirks" so be warned!

This library ships with a basic extension to help working with the various viewer events - you can also use the extensions that ship with the Forge Viewer. Unfortunately, we have no plans to ship any further extensions.
